### PR TITLE
Fix #1

### LINKED ISSUE #1: Remove node_modules folder
basically the title, you committed the node_modules folder by accident i presume, I am too lazy to make a pr to fix this lol. This is also really cool good job.

### PR DESCRIPTION
**Pull request by BD103**
(hi)

### CODE REVIEW

**Comment by RayhanADev** [comment]
Hi!
It shouldn't really change anything right now, I have to manually delete the folder on the repo xD.

**Comment by BD103** [comment]
Oop got it

**Comment by RayhanADev** [comment]
Hey @BD103 since you're interested in this project I was wondering, do you have any ideas on what to possibly add? I would like to make you a maintainer if you're interested in contributing :).

Also this did offshoot into [ReplFiles](https://replit.com/talk/share/ReplFiles-~-Fetch-ANY-File-from-a-Public-Repl/138817) which might also interest you!

**Comment by BD103** [comment]
Hm... I have a few ideas. Code highlighter, for one. Maybe directory listing for files. Change filename to be a URL argument, since it's mandatory. I could help, it would be good practice with node.

**Comment by BD103** [comment]
Oh, sorry. Those suggestions were for ReplFiles, not ArchiveIt. :P

**Comment by RayhanADev** [comment]
@BD103 hmmm, interesting!
Care to start a fork [on the repo](https://github.com/RayhanADev/ReplFiles) and then, when you're ready, open a pull request?

**Pull request closed without merging**
